*** Variables ***
${SAUCE_URL}       ${SAUCE_URL}
${BROWSER}   ${BROWSER}
${SAUCE_USER}      ${SAUCE_USER}
${SAUCE_PASSWORD}  ${SAUCE_PASSWORD}
${SAUCE_PASSWORDWRONG}  ${SAUCE_PASSWORDWRONG}
${FIRST_NAME}    ${FIRST_NAME}    
${LAST_NAME}    ${LAST_NAME}    
${POSTAL_CODE}    ${POSTAL_CODE}